connector.name=iceberg
iceberg.catalog.type=rest
iceberg.rest-catalog.uri=http://host.docker.internal:8282
iceberg.rest-catalog.warehouse=lakehouse
iceberg.rest-catalog.security=OAUTH2
iceberg.rest-catalog.oauth2.credential=root:s3cr3t
iceberg.rest-catalog.oauth2.server-uri=http://host.docker.internal:8282/v1/oauth/tokens
fs.hadoop.enabled=true
iceberg.rest-catalog.oauth2.scope=PRINCIPAL_ROLE:ALL
