apiVersion: v1
kind: Service
metadata:
  name: {{ include "kahshe.fullname" . }}
  labels:
    {{- include "kahshe.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "kahshe.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
  ports:
    - { port: {{ .Values.service.dataPort }}, targetPort: data, name: data }
    - { port: {{ .Values.service.adminPort }}, targetPort: admin, name: admin }
